name: Jadoo IPTV Automation

on:
  push:
    branches:
      - main  # Change to your default branch if necessary
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours (adjust as needed)
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3

      - name: Run Script
        run: python main.py

      - name: Upload Playlist
        uses: actions/upload-artifact@v3
        with:
          name: jadoo_playlist
          path: jadoo_playlist.m3u
